# Generated by Django 5.2.15 on 2026-06-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Tagayev Methods', max_length=120, verbose_name='Sayt nomi')),
                ('site_name_uz', models.CharField(default='Tagayev Methods', max_length=120, null=True, verbose_name='Sayt nomi')),
                ('site_name_ru', models.CharField(default='Tagayev Methods', max_length=120, null=True, verbose_name='Sayt nomi')),
                ('site_name_en', models.CharField(default='Tagayev Methods', max_length=120, null=True, verbose_name='Sayt nomi')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Shior')),
                ('tagline_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Shior')),
                ('tagline_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Shior')),
                ('tagline_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Shior')),
                ('logo', models.ImageField(blank=True, help_text="Bo'sh qoldirilsa, standart logo ishlatiladi.", upload_to='branding/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, upload_to='branding/', verbose_name='Favicon')),
                ('site_domain', models.CharField(blank=True, help_text='Masalan: tagayev.uz (protokolsiz). Sitemap/canonical uchun.', max_length=120, verbose_name='Domen')),
                ('phone_primary', models.CharField(blank=True, max_length=30, verbose_name='Asosiy telefon')),
                ('phone_secondary', models.CharField(blank=True, max_length=30, verbose_name="Qo'shimcha telefon")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('address_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('address_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('working_hours', models.CharField(blank=True, max_length=120, verbose_name='Ish vaqti')),
                ('working_hours_uz', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ish vaqti')),
                ('working_hours_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ish vaqti')),
                ('working_hours_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ish vaqti')),
                ('latitude', models.CharField(blank=True, max_length=32, verbose_name='Kenglik (lat)')),
                ('longitude', models.CharField(blank=True, max_length=32, verbose_name='Uzunlik (lng)')),
                ('google_maps_embed', models.TextField(blank=True, verbose_name='Google Maps embed')),
                ('yandex_maps_embed', models.TextField(blank=True, verbose_name='Yandex Maps embed')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO sarlavha')),
                ('seo_title_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO sarlavha')),
                ('seo_title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO sarlavha')),
                ('seo_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO sarlavha')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO tavsif')),
                ('seo_description_uz', models.TextField(blank=True, null=True, verbose_name='SEO tavsif')),
                ('seo_description_ru', models.TextField(blank=True, null=True, verbose_name='SEO tavsif')),
                ('seo_description_en', models.TextField(blank=True, null=True, verbose_name='SEO tavsif')),
                ('og_image', models.ImageField(blank=True, upload_to='seo/', verbose_name='OG rasm (ulashish)')),
                ('google_site_verification', models.CharField(blank=True, max_length=255, verbose_name='Google verification')),
                ('yandex_verification', models.CharField(blank=True, max_length=255, verbose_name='Yandex verification')),
                ('bing_msvalidate', models.CharField(blank=True, max_length=255, verbose_name='Bing verification')),
                ('ga4_measurement_id', models.CharField(blank=True, help_text='G-XXXXXXX', max_length=40, verbose_name='Google Analytics 4 ID')),
                ('yandex_metrica_id', models.CharField(blank=True, max_length=40, verbose_name='Yandex Metrica ID')),
                ('telegram_notifications_enabled', models.BooleanField(default=True, verbose_name='Telegram bildirishnomalari yoniq')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
