# Generated by Django 5.2.16 on 2026-08-24 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0009_remove_siteconfig_yandex_maps_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='brand_accent',
            field=models.CharField(blank=True, help_text='#RRGGBB. Tugmalar va belgilar. Boʻsh = standart tilla.', max_length=7, validators=[django.core.validators.RegexValidator(message='Rang #RRGGBB koʻrinishida boʻlishi kerak (masalan: #7a45e0).', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Aksent rang'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='brand_primary',
            field=models.CharField(blank=True, help_text='#RRGGBB. Havolalar, sarlavhalar, gradientlar. Boʻsh = standart binafsha.', max_length=7, validators=[django.core.validators.RegexValidator(message='Rang #RRGGBB koʻrinishida boʻlishi kerak (masalan: #7a45e0).', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Asosiy rang'),
        ),
    ]
