# Generated by Django 5.2.16 on 2026-08-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_copy_about_image_to_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='badge_text',
            field=models.CharField(default='Zamonaviy taʼlim markazi', help_text='Hero tepasidagi kichik yorliq (masalan, shahar).', max_length=160, verbose_name='Yorliq matni'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='badge_text_en',
            field=models.CharField(default='Zamonaviy taʼlim markazi', help_text='Hero tepasidagi kichik yorliq (masalan, shahar).', max_length=160, null=True, verbose_name='Yorliq matni'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='badge_text_ru',
            field=models.CharField(default='Zamonaviy taʼlim markazi', help_text='Hero tepasidagi kichik yorliq (masalan, shahar).', max_length=160, null=True, verbose_name='Yorliq matni'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='badge_text_uz',
            field=models.CharField(default='Zamonaviy taʼlim markazi', help_text='Hero tepasidagi kichik yorliq (masalan, shahar).', max_length=160, null=True, verbose_name='Yorliq matni'),
        ),
        migrations.AlterField(
            model_name='sitecopy',
            name='footer_note',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Footer — pastki matn'),
        ),
        migrations.AlterField(
            model_name='sitecopy',
            name='footer_note_en',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Footer — pastki matn'),
        ),
        migrations.AlterField(
            model_name='sitecopy',
            name='footer_note_ru',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Footer — pastki matn'),
        ),
        migrations.AlterField(
            model_name='sitecopy',
            name='footer_note_uz',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Footer — pastki matn'),
        ),
    ]
