# -*- coding: utf-8 -*-
"""Auto-drafted + hand-corrected admin translations.
Generated by _make_extra.py from _draft_translations.txt.
Merged by _build_catalogs.py (ru/en) and _build_uz_admin.py (uz)."""

PROJECT_RU = {
    # --- Telegram qabul qiluvchilar (multi-admin notifications) ---
    'Telegram bot tokeni': 'Токен Telegram-бота',
    '@BotFather bergan token. Boʻsh qoldirilsa, serverdagi .env qiymati ishlatiladi.': 'Токен от @BotFather. Если оставить пустым, используется значение .env на сервере.',
    'Telegram qabul qiluvchi': 'Получатель Telegram',
    'Telegram qabul qiluvchilar': 'Получатели Telegram',
    'Kimligini eslatuvchi nom (masalan: Direktor). Ixtiyoriy.': 'Напоминающее имя (например: Директор). Необязательно.',
    'Chat ID': 'Chat ID',
    'Raqamli chat ID (masalan: 123456789). Foydalanuvchi botga /start yozgach, @userinfobot orqali bilib olish mumkin.': 'Числовой chat ID (например: 123456789). Узнать можно через @userinfobot после того, как пользователь напишет боту /start.',
    'Faol': 'Активен',
    'Belgilanmasa, bu adminga arizalar yuborilmaydi.': 'Если снять отметку, заявки этому администратору не отправляются.',
    'Chat ID raqam (masalan: 123456789 yoki -1001234567890) yoki @username koʻrinishida boʻlishi kerak.': 'Chat ID должен быть числом (например: 123456789 или -1001234567890) либо в виде @username.',
    'Bot tokenini kiriting, soʻng «Telegram qabul qiluvchilar» boʻlimida arizalarni qabul qiladigan adminlarni qoʻshing — bir nechta admin qoʻshish mumkin.': 'Введите токен бота, затем в разделе «Получатели Telegram» добавьте администраторов, принимающих заявки — можно добавить несколько.',
    ' va boshqalar': 'и другие',
    '%(o)d ta yozuv, %(f)d ta maydon avto-tarjima qilindi. Iltimos, tekshiring.': '%(o)d записей, %(f)d полей были переведены автоматически. Пожалуйста, проверьте.',
    'Ariza oynasi (modal)': 'Окно приложения (модальное)',
    'Arizalar (soʻnggi 14 kun)': 'Заявки (за последние 14 дней)',
    'Arizalar holati boʻyicha': 'По статусу заявок',
    'Asosiy kontentga oʻtish': 'Перейти к основному содержанию',
    'Asosiy tugma': 'Основная кнопка',
    'Avto-tarjima: %(n)d ta maydon toʻldirildi. Tekshirib, saqlang.': 'Автоперевод: заполнено %(n)d полей. Проверьте и сохраните.',
    'Bilimga ishonchni mustahkamlaymiz': 'Укрепляем доверие к знаниям',
    'Biz bilan bogʻlaning': 'Свяжитесь с нами',
    'Bogʻlanildi': 'Связались',
    'Bogʻlanish': 'Контакты',
    'Bosh sahifa videosi': 'Видео на главной странице',
    'Boʻlim': 'Раздел',
    'Boʻsh qoldirilsa, platforma nomi ishlatiladi.': 'Если оставить пустым, будет использоваться имя платформы.',
    'Brauzer maʼlumoti': 'Данные браузера',
    'Davlat': 'Страна',
    'Davlat kodi': 'Код страны',
    'Davlatlar boʻyicha tashriflar': 'Посещения по странам',
    'Django site admin': 'Администратор сайта Джанго',
    'Faol / chop etilgan': 'Активный/опубликованный',
    'Faqat maxsus embed kerak bo‘lsa to‘ldiring. Bo‘sh qoldirilsa, ': 'Заполняйте только в том случае, если вам нужна индивидуальная вставка. Если оставить пустым,',
    'Fikrlar — sarlavha': 'Отзывы — заголовок',
    'Footer': 'Подвал',
    'Footer — pastki matn': 'Подвал — нижний текст',
    'Galereya videolari': 'Галерея видео',
    'Galereya videosi': 'Галерея видео',
    'Havola': 'Ссылка',
    "Hero bo'limi": 'Раздел героев',
    'Hero tepasidagi kichik yorliq (masalan, shahar).': 'Небольшая вкладка над Героем (например, городом).',
    'Ijtimoiy tarmoq': 'Социальная сеть',
    'Ikkilamchi tugma': 'Дополнительная кнопка',
    'Ixtiyoriy — yuklangan video uchun muqova.': 'Необязательно — обложка для загруженного видео.',
    'Jami': 'Итого',
    'Juda koʻp soʻrov. Birozdan soʻng urinib koʻring.': 'Слишком много запросов. Пожалуйста, повторите попытку позже.',
    'Kichik matn': 'Мелкий текст',
    "Kontakt bo'limi": 'Раздел контактов',
    'Kontakt — matn': 'Контакт — текст',
    'Kontakt — sarlavha': 'Контакт — заголовок',
    'Kontakt — yorliq': 'Контакт\xa0— это ярлык',
    'Kontakt — yuborish tugmasi': 'Контакт - кнопка отправить',
    'Kurs rasmi': 'Изображение курса',
    'Kurs rasmlari': 'Фотографии курса',
    'Kurslar / oʻqituvchilar': 'Курсы / преподаватели',
    'MP4/WebM. Havola berilsa, shart emas.': 'MP4/ВебМ. Это не обязательно, если есть ссылка.',
    "Natijalar bo'limi": 'Раздел результатов',
    'Natijalar — havola matni': 'Результаты\xa0— текст ссылки',
    'Natijalar — sarlavha': 'Результаты\xa0— название',
    'Natijalar — yorliq': 'Результаты – вкладка',
    'Nomi (ixtiyoriy)': 'Имя (необязательно)',
    'Oyna — matn': 'Окно - текст',
    'Oyna — sarlavha': 'Окно — заголовок',
    'Oyna — yuborish tugmasi': 'Окно – кнопка отправки',
    'Oʻquv jarayonimizdan lavhalar': 'Фрагменты нашего тренировочного процесса',
    'Oʻquvchi boʻldi': 'Стал учеником',
    'Oʻquvchilarimiz sertifikatlari': 'Сертификаты наших учеников',
    'Platforma': 'Платформа',
    'Qoʻngʻiroq': 'Позвонить',
    'Qoʻshimcha izoh': 'Дополнительный комментарий',
    'Qoʻshimcha izoh (ixtiyoriy)': 'Дополнительный комментарий (необязательно)',
    'Sarlavha — boshi': 'Заголовок — начало',
    'Sarlavha — oxiri': 'Заголовок — конец',
    'Savolingiz yoki qoʻshimcha maʼlumot…': 'Есть вопрос или дополнительная информация…',
    'Sayt kontenti': 'Содержимое сайта',
    'Sayt matnlari': 'Тексты сайта',
    'Sayt nomidan keyingi qism.': 'Часть после названия сайта.',
    'Sayt nomidan oldingi qism.': 'Часть перед названием сайта.',
    'Saytni koʻrish': 'Посмотреть сайт',
    'Soni': 'Количество',
    'Tajribali oʻqituvchilar': 'Опытные преподаватели',
    'Tajribali oʻqituvchilar, zamonaviy metodika va natijaga yoʻnaltirilgan kichik guruhlar — bir joyda.': 'Опытные преподаватели, современная методика и ориентированные на результат малые группы – в одном месте.',
    'Tanlangan yozuvlarda boʻsh tarjima maydoni topilmadi.': 'В выбранных записях не найдено пустое поле перевода.',
    'Tarjima qilinadigan boʻsh maydon topilmadi.': 'Пустое поле для перевода не найдено.',
    'Tarjima toʻliq emas — boʻsh: %(fields)s%(more)s. ': 'Перевод неполный\xa0– пусто: %(fields)s%(more)s.',
    'Tashriflar (soʻnggi 14 kun)': 'Посещения (последние 14 дней)',
    'Telefon raqamni +998XXXXXXXXX koʻrinishida kiriting.': 'Введите номер телефона в виде +998XXXXXXXXX.',
    "To'liq sarlavha: «Sarlavha boshi» + sayt nomi + «Sarlavha oxiri».": 'Полное название: «Начало заголовка» + название сайта + «Конец заголовка».',
    'Top manbalar': 'Топ источников',
    'Top sahifalar': 'Топ страниц',
    'Tugmalar': 'Кнопки',
    'UTM yoki referrer (avtomatik toʻldiriladi).': 'UTM или реферер (заполняется автоматически).',
    'UZ → RU/EN avto-tarjima': 'УЗ → RU/EN автоперевод',
    'UZ → RU/EN avto-tarjima (boʻsh maydonlarni toʻldirish)': 'УЗ → RU/EN автоперевод (заполните поля)',
    'Veb-sayt': 'Веб-сайт',
    'Video': 'Видео',
    'Video fayl': 'Видео файл',
    'Video havola': 'Ссылка на видео',
    'Xarita — qo‘lda override (ixtiyoriy)': 'Карта – ручное управление (опционально)',
    'Xaritani bosing yoki belgini suring — koordinatalar avtomatik to‘ladi.': 'Нажмите на карту или перетащите иконку — координаты заполнятся автоматически.',
    'Yangilik / eʼlon': 'Новость / объявление',
    'Yangiliklar va eʻlonlar': 'Новости и объявления',
    'Yangiliklar va eʼlonlar': 'Новости и объявления',
    'Yoqilgan': 'Включено',
    'Yorliq matni': 'Текст метки',
    'Yorliq va sarlavha': 'Этикетка и заголовок',
    'YouTube, Vimeo yoki embed havola.': 'YouTube, Vimeo или вставьте ссылку.',
    'YouTube/Vimeo havola yoki video fayl yuklang.': 'Загрузите ссылку на YouTube/Vimeo или видеофайл.',
    'Yoʻnalishlar': 'Направления',
    'Yoʻnaltiruvchi': 'Источник перехода',
    'Zamonaviy taʻlim markazi. Biz bilan farzandingiz kelajagiga ishonchli qadam qoʻying.': 'Современный образовательный центр. Сделайте уверенный шаг в будущее своего ребенка вместе с нами.',
    'oʻrtacha': 'в среднем',
    'yangi oʻquvchi': 'новых учеников',
    # --- CEFR QR-skaner (admin_qr_scanner.js) ---
    '📷 QR kodni skanerlash': '📷 Сканировать QR-код',
    'Yopish': 'Закрыть',
    'Topildi:': 'Найдено:',
    'Kamera ochilmoqda…': 'Открывается камера…',
    'QR kodni kameraga toʻgʻrilang…': 'Наведите камеру на QR-код…',
    'Kameraga ruxsat berilmadi:': 'Доступ к камере запрещён:',
    'Bu brauzerda kamera ishlamaydi. Havolani qoʻlda kiriting.': 'В этом браузере камера не работает. Введите ссылку вручную.',
    # --- Admin / public UI (Unfold helper overrides + PWA) ---
    'Ilovani oʻrnatish': 'Установить приложение',
    'Menyuni ochish yoki yopish': 'Открыть или закрыть меню',
    'Menyuni yopish': 'Закрыть меню',
    'Show all': 'Показать все',
    # --- Theme switch override (templates/unfold/helpers/theme_switch.html) ---
    'Dark': 'Тёмная',
    'Light': 'Светлая',
    'System': 'Системная',
    # --- Hero section (1-/2-tab metric values, floating tabs fieldset) ---
    '1-yorliq — qiymat': '1-я вкладка — значение',
    '2-yorliq — qiymat': '2-я вкладка — значение',
    'Suzuvchi yorliqlar': 'Плавающие метки',
    "Chap yuqoridagi yorliq, masalan «IELTS 7.5» ('oʻrtacha' izohi bilan).":
        'Метка в левом верхнем углу, например «IELTS 7.5» (с примечанием «в среднем»).',
    "«Bu oy … yangi oʻquvchi» yorlig'idagi raqam, masalan «100+».":
        'Число в метке «В этом месяце … новых учеников», например «100+».',
    'Hero rasmi ustidagi kichik kartalardagi raqamlar.':
        'Цифры на маленьких карточках над изображением героя.',
    # --- Partners (apps/pages/models.py) ---
    'Hamkor': 'Партнёр',
    'Hamkorlar': 'Партнёры',
    'Veb-sayt (ixtiyoriy)': 'Веб-сайт (необязательно)',
    # --- Certificates ---
    'Havolani ochish': 'Открыть ссылку',
    'Sertifikat olingan sanasi': 'Дата получения сертификата',
    'Bu yilda sertifikat topilmadi.': 'В этом году сертификатов не найдено.',
    'PDF havoladan avtomatik aniqlanadi (topilsa).':
        'Определяется автоматически по ссылке на PDF (если найдено).',
    # --- Leads / CRM (apps/leads) ---
    'Lidlar': 'Лиды',
    'Manbalar': 'Источники',
    'Manbalar boʻyicha lidlar (CRM)': 'Лиды по источникам (CRM)',
    'Rang': 'Цвет',
    'Rasm (hisobot uchun)': 'Изображение (для отчёта)',
    'Himoyalangan': 'Защищено',
    'Referrer': 'Реферер',
    'Ruxsat etilmagan manba.': 'Недопустимый источник.',
    'Hali manba yoʻq.': 'Пока нет источников.',
    'Material Symbols nomi (masalan: public). Rasm boʻlmaganda ishlatiladi.':
        'Название Material Symbols (например: public). Используется, если нет изображения.',
    # --- Analytics dashboard (apps/analytics/dashboard.py) ---
    'Bugun': 'Сегодня',
    'Hafta': 'Неделя',
    'Oy': 'Месяц',
    'Yil': 'Год',
    'Arizalar (davr)': 'Заявки (период)',
    'Yangi arizalar (davr)': 'Новые заявки (период)',
    'Arizalar dinamikasi': 'Динамика заявок',
    'Tashriflar (davr)': 'Посещения (период)',
    'Tashriflar dinamikasi': 'Динамика посещений',
    'CRM': 'CRM',
    # --- Site config: analytics IDs, Telegram token (apps/siteconfig) ---
    'Google Analytics ID G-XXXXXXX (yoki UA-XXXX-Y) koʻrinishida boʻlishi kerak.':
        'Google Analytics ID должен быть в формате G-XXXXXXX (или UA-XXXX-Y).',
    'Yandex Metrica ID faqat raqamlardan iborat boʻlishi kerak (masalan: 12345678).':
        'Yandex Metrica ID должен состоять только из цифр (например: 12345678).',
    '#RRGGBB. Boʻsh boʻlsa asosiy rang ishlatiladi.':
        '#RRGGBB. Если оставить пустым, используется основной цвет.',
    'Token holati': 'Статус токена',
    'Saqlangan tokenni oʻchirish': 'Удалить сохранённый токен',
    'Belgilansa, paneldagi token oʻchiriladi va .env qiymati ishlatiladi.':
        'Если отмечено, токен в панели будет удалён, и будет использовано значение из .env.',
    'Xavfsizlik uchun saqlangan token qayta koʻrsatilmaydi. ':
        'Из соображений безопасности сохранённый токен больше не отображается. ',
    'Bot tokenini kiriting, soʻng «Telegram qabul qiluvchilar» boʻlimida arizalarni qabul qiladigan adminlarni qoʻshing — bir nechta admin qoʻshish mumkin. Xavfsizlik uchun token bir marta yoziladi va qaytadan koʻrsatilmaydi.':
        'Введите токен бота, затем в разделе «Получатели Telegram» добавьте администраторов, принимающих заявки, — можно добавить несколько. Из соображений безопасности токен вводится один раз и больше не отображается.',
    '• .env qiymati ishlatiladi': '• используется значение из .env',
    '✓ Oʻrnatilgan (panel)': '✓ Установлен (панель)',
    '✗ Oʻrnatilmagan': '✗ Не установлен',

    # --- Analitika paneli v2 + maxfiylik/404 (2026-08) ---
    'Maʼlumotlarni yuklab boʻlmadi.': 'Не удалось загрузить данные.',
    'Qayta urinish': 'Повторить',
    'Aniqlanmagan':
        'Не определено',
    'Asliga qaytarish':
        'Сбросить масштаб',
    'Boshlanish sanasi':
        'Дата начала',
    'Brauzer, qurilma va operatsion tizim':
        'Браузер, устройство и операционная система',
    'Brauzerlar':
        'Браузеры',
    'Bu davrda maʼlumot yoʻq.':
        'За этот период нет данных.',
    'Butun davr':
        'За всё время',
    'Butun ekran':
        'Полный экран',
    'Chiqib ketish darajasi':
        'Показатель отказов',
    'Davlatlar':
        'Страны',
    'Jonli':
        'В реальном времени',
    'Joylashuv':
        'Местоположение',
    'Kam':
        'Мало',
    'Kattalashtirish':
        'Приблизить',
    'Kichiklashtirish':
        'Отдалить',
    'Koʻp':
        'Много',
    'Koʻrish':
        'Просмотры',
    'Mahalliy tarmoq':
        'Локальная сеть',
    'Nomaʼlum':
        'Неизвестно',
    'Operatsion tizimlar':
        'Операционные системы',
    'Oʻrtacha davomiylik':
        'Средняя длительность',
    'Qoʻllash':
        'Применить',
    'Qurilma':
        'Устройство',
    'Roʻyxat':
        'Список',
    'Sahifa koʻrishlari':
        'Просмотры страниц',
    'Soʻnggi 1 soat':
        'Последний час',
    'Soʻnggi 1 yil':
        'Последний год',
    'Soʻnggi 24 soat':
        'Последние 24 часа',
    'Soʻnggi 3 oy':
        'Последние 3 месяца',
    'Soʻnggi 30 kun':
        'Последние 30 дней',
    'Soʻnggi 6 oy':
        'Последние 6 месяцев',
    'Soʻnggi 7 kun':
        'Последние 7 дней',
    'Tanlangan davr':
        'Выбранный период',
    'Tashrifchi':
        'Посетители',
    'Texnologiyalar':
        'Технологии',
    'Toʻgʻridan-toʻgʻri':
        'Прямые заходы',
    'Tugash sanasi':
        'Дата окончания',
    'Xarita':
        'Карта',
    'Ariza qoldirganingizda: ism-familiya, telefon raqam, tanlangan kurs va ixtiyoriy izoh.':
        'При оставлении заявки: имя и фамилия, номер телефона, выбранный курс и необязательный комментарий.',
    'Arizalar faqat markazning masʼul xodimlariga (jumladan Telegram orqali) yetkaziladi. Biz maʼlumotlaringizni uchinchi shaxslarga sotmaymiz. Sayt statistikasi uchun tashqi tahlil xizmatlaridan (masalan Google Analytics, Yandex Metrica) foydalanilishi mumkin.':
        'Заявки передаются только ответственным сотрудникам центра (в том числе через Telegram). Мы не продаём ваши данные третьим лицам. Для статистики сайта могут использоваться внешние аналитические сервисы (например Google Analytics, Yandex Metrica).',
    'Arizalar siz bilan bogʻlanish uchun zarur boʻlgan muddat davomida saqlanadi. Tashrif loglari cheklangan muddatdan soʻng avtomatik oʻchiriladi.':
        'Заявки хранятся столько, сколько необходимо для связи с вами. Логи посещений автоматически удаляются по истечении ограниченного срока.',
    'Arizangiz boʻyicha siz bilan bogʻlanish va kurslar haqida maʼlumot berish.':
        'Связь с вами по вашей заявке и предоставление информации о курсах.',
    'Cookie va lokal saqlash':
        'Cookie и локальное хранилище',
    'Tagayev Methods maxfiylik siyosati: qanday maʼlumotlar yigʻiladi va qanday ishlatiladi.':
        'Политика конфиденциальности Tagayev Methods: какие данные собираются и как используются.',
    'Maxfiylik siyosati':
        'Политика конфиденциальности',
    'Maʼlumotlar kim bilan ulashiladi':
        'С кем передаются данные',
    'Maʼlumotlardan qanday foydalaniladi':
        'Как используются данные',
    'Maʼlumotlarni saqlash muddati':
        'Срок хранения данных',
    'Oxirgi yangilanish':
        'Последнее обновление',
    'Oʻzingiz haqingizdagi maʼlumotlarni koʻrish, tuzatish yoki oʻchirishni soʻrashingiz mumkin. Buning uchun quyidagi aloqa maʼlumotlari orqali bogʻlaning.':
        'Вы можете запросить просмотр, исправление или удаление своих данных. Для этого свяжитесь с нами по указанным ниже контактам.',
    'O‘quvchilarimizning erishgan natijalari (CEFR va boshqa sertifikatlar) yutuqlar namunasi sifatida saytda e’lon qilinishi mumkin. Bunda sertifikat tasviri va o‘quvchi ismi ko‘rsatiladi. Ular faqat o‘quvchi yoki uning qonuniy vakili roziligi bilan joylashtiriladi. Sertifikatingizni saytdan olib tashlashni istasangiz, quyidagi aloqa orqali murojaat qiling — biz zudlik bilan o‘chiramiz.':
        'Результаты наших учеников (CEFR и другие сертификаты) могут публиковаться на сайте как примеры достижений. При этом показываются изображение сертификата и имя ученика. Они размещаются только с согласия ученика или его законного представителя. Если вы хотите убрать свой сертификат с сайта, свяжитесь с нами по указанным контактам — мы удалим его незамедлительно.',
    'Qanday maʼlumotlar yigʻiladi':
        'Какие данные собираются',
    'Sayt tanlagan tilingiz va yorugʻ/qorongʻu rejimni brauzeringizda saqlaydi. Statistika xizmatlari oʻz cookie fayllaridan foydalanishi mumkin.':
        'Сайт сохраняет в вашем браузере выбранный язык и светлую/тёмную тему. Сервисы статистики могут использовать свои cookie-файлы.',
    'Saytga tashrif buyurganingizda avtomatik: IP-manzil, brauzer turi va koʻrilgan sahifalar (statistika uchun).':
        'При посещении сайта автоматически: IP-адрес, тип браузера и просмотренные страницы (для статистики).',
    'Sertifikatlar (o‘quvchi yutuqlari)':
        'Сертификаты (достижения учеников)',
    'Sizning huquqlaringiz':
        'Ваши права',
    'Xizmat sifatini va sayt ishlashini yaxshilash (umumlashtirilgan statistika).':
        'Улучшение качества услуг и работы сайта (обобщённая статистика).',
    'Sahifa topilmadi':
        'Страница не найдена',
    'Kechirasiz, siz qidirgan sahifa mavjud emas yoki koʻchirilgan.':
        'Извините, запрашиваемая страница не существует или была перемещена.',
    'Xatolik yuz berdi. Iltimos, qaytadan urinib koʻring.':
        'Произошла ошибка. Пожалуйста, попробуйте ещё раз.',
    'Yuborilmoqda…':
        'Отправка…',
    'Rasmni kattalashtirish':
        'Увеличить изображение',
    'Hero blokidagi katta rasm/poster.':
        'Большое изображение/постер в блоке Hero.',
    'Google xarita — qo‘lda override (ixtiyoriy)':
        'Google Карта — ручное переопределение (необязательно)',
    'Faqat maxsus Google embed kerak bo‘lsa to‘ldiring. Bo‘sh ':
        'Заполняйте, только если нужен особый Google embed. Пустое ',
}

PROJECT_EN = {
    # --- Telegram qabul qiluvchilar (multi-admin notifications) ---
    'Telegram bot tokeni': 'Telegram bot token',
    '@BotFather bergan token. Boʻsh qoldirilsa, serverdagi .env qiymati ishlatiladi.': "Token from @BotFather. If left empty, the server's .env value is used.",
    'Telegram qabul qiluvchi': 'Telegram recipient',
    'Telegram qabul qiluvchilar': 'Telegram recipients',
    'Kimligini eslatuvchi nom (masalan: Direktor). Ixtiyoriy.': 'A reminder name (e.g. Director). Optional.',
    'Chat ID': 'Chat ID',
    'Raqamli chat ID (masalan: 123456789). Foydalanuvchi botga /start yozgach, @userinfobot orqali bilib olish mumkin.': 'Numeric chat ID (e.g. 123456789). You can find it via @userinfobot after the user sends /start to the bot.',
    'Faol': 'Active',
    'Belgilanmasa, bu adminga arizalar yuborilmaydi.': 'If unchecked, applications are not sent to this admin.',
    'Chat ID raqam (masalan: 123456789 yoki -1001234567890) yoki @username koʻrinishida boʻlishi kerak.': 'Chat ID must be a number (e.g. 123456789 or -1001234567890) or an @username.',
    'Bot tokenini kiriting, soʻng «Telegram qabul qiluvchilar» boʻlimida arizalarni qabul qiladigan adminlarni qoʻshing — bir nechta admin qoʻshish mumkin.': 'Enter the bot token, then add the admins who receive applications in the «Telegram recipients» section — you can add several.',
    ' va boshqalar': 'and others',
    '%(o)d ta yozuv, %(f)d ta maydon avto-tarjima qilindi. Iltimos, tekshiring.': '%(o)d entries, %(f)d fields were auto-translated. Please check.',
    'Ariza oynasi (modal)': 'Application window (modal)',
    'Arizalar (soʻnggi 14 kun)': 'Applications (last 14 days)',
    'Arizalar holati boʻyicha': 'By application status',
    'Asosiy kontentga oʻtish': 'Skip to main content',
    'Asosiy tugma': 'Main button',
    'Avto-tarjima: %(n)d ta maydon toʻldirildi. Tekshirib, saqlang.': 'Auto-translation: %(n)d fields are filled. Check and save.',
    'Bilimga ishonchni mustahkamlaymiz': 'We strengthen trust in knowledge',
    'Biz bilan bogʻlaning': 'Contact us',
    'Bogʻlanildi': 'Contacted',
    'Bogʻlanish': 'Contact',
    'Bosh sahifa videosi': 'Homepage video',
    'Boʻlim': 'Section',
    'Boʻsh qoldirilsa, platforma nomi ishlatiladi.': 'If left blank, the platform name will be used.',
    'Brauzer maʼlumoti': 'User agent',
    'Davlat': 'Country',
    'Davlat kodi': 'Country code',
    'Davlatlar boʻyicha tashriflar': 'Visits by country',
    'Django site admin': 'Django site admin',
    'Faol / chop etilgan': 'Active / published',
    'Faqat maxsus embed kerak bo‘lsa to‘ldiring. Bo‘sh qoldirilsa, ': 'Only fill in if you need a custom embed. If left blank,',
    'Fikrlar — sarlavha': 'Reviews — title',
    'Footer': 'Footer',
    'Footer — pastki matn': 'Footer — bottom text',
    'Galereya videolari': 'Gallery videos',
    'Galereya videosi': 'Gallery video',
    'Havola': 'Link',
    "Hero bo'limi": 'Hero section',
    'Hero tepasidagi kichik yorliq (masalan, shahar).': 'A small tab above the Hero (for example, a city).',
    'Ijtimoiy tarmoq': 'Social network',
    'Ikkilamchi tugma': 'Secondary button',
    'Ixtiyoriy — yuklangan video uchun muqova.': 'Optional — a cover for the uploaded video.',
    'Jami': 'Total',
    'Juda koʻp soʻrov. Birozdan soʻng urinib koʻring.': 'Too many requests. Please try again later.',
    'Kichik matn': 'Small text',
    "Kontakt bo'limi": 'Contact section',
    'Kontakt — matn': 'Contact — text',
    'Kontakt — sarlavha': 'Contact is the title',
    'Kontakt — yorliq': 'Contact is a shortcut',
    'Kontakt — yuborish tugmasi': 'Contact - send button',
    'Kurs rasmi': 'Course image',
    'Kurs rasmlari': 'Course pictures',
    'Kurslar / oʻqituvchilar': 'Courses / teachers',
    'MP4/WebM. Havola berilsa, shart emas.': 'MP4/WebM. It is not necessary if a link is provided.',
    "Natijalar bo'limi": 'Results section',
    'Natijalar — havola matni': 'Results - link text',
    'Natijalar — sarlavha': 'Results - title',
    'Natijalar — yorliq': 'Results - tab',
    'Nomi (ixtiyoriy)': 'Name (optional)',
    'Oyna — matn': 'Window - text',
    'Oyna — sarlavha': 'The window is the title',
    'Oyna — yuborish tugmasi': 'Window - submit button',
    'Oʻquv jarayonimizdan lavhalar': 'Clips from our training process',
    'Oʻquvchi boʻldi': 'Enrolled',
    'Oʻquvchilarimiz sertifikatlari': 'Certificates of our students',
    'Platforma': 'Platform',
    'Qoʻngʻiroq': 'Call',
    'Qoʻshimcha izoh': 'Additional comment',
    'Qoʻshimcha izoh (ixtiyoriy)': 'Additional Comment (optional)',
    'Sarlavha — boshi': 'Title — beginning',
    'Sarlavha — oxiri': 'Title — end',
    'Savolingiz yoki qoʻshimcha maʼlumot…': 'Have a question or more information…',
    'Sayt kontenti': 'Site content',
    'Sayt matnlari': 'Site texts',
    'Sayt nomidan keyingi qism.': 'The part after the site name.',
    'Sayt nomidan oldingi qism.': 'The part before the site name.',
    'Saytni koʻrish': 'View site',
    'Soni': 'Count',
    'Tajribali oʻqituvchilar': 'Experienced teachers',
    'Tajribali oʻqituvchilar, zamonaviy metodika va natijaga yoʻnaltirilgan kichik guruhlar — bir joyda.': 'Experienced teachers, modern methodology and result-oriented small groups - in one place.',
    'Tanlangan yozuvlarda boʻsh tarjima maydoni topilmadi.': 'An empty translation field was not found in the selected records.',
    'Tarjima qilinadigan boʻsh maydon topilmadi.': 'No empty field found to be translated.',
    'Tarjima toʻliq emas — boʻsh: %(fields)s%(more)s. ': 'Translation incomplete - empty: %(fields)s%(more)s.',
    'Tashriflar (soʻnggi 14 kun)': 'Visits (last 14 days)',
    'Telefon raqamni +998XXXXXXXXX koʻrinishida kiriting.': 'Enter the phone number in the form +998XXXXXXXXX.',
    "To'liq sarlavha: «Sarlavha boshi» + sayt nomi + «Sarlavha oxiri».": 'Full title: "Heading start" + site name + "Heading end".',
    'Top manbalar': 'Top sources',
    'Top sahifalar': 'Top pages',
    'Tugmalar': 'Buttons',
    'UTM yoki referrer (avtomatik toʻldiriladi).': 'UTM or referrer (auto-filled).',
    'UZ → RU/EN avto-tarjima': 'UZ → RU/EN auto-translation',
    'UZ → RU/EN avto-tarjima (boʻsh maydonlarni toʻldirish)': 'UZ → RU/EN auto-translation (fill in the blanks)',
    'Veb-sayt': 'Website',
    'Video': 'Video',
    'Video fayl': 'Video file',
    'Video havola': 'Video link',
    'Xarita — qo‘lda override (ixtiyoriy)': 'Map - manual override (optional)',
    'Xaritani bosing yoki belgini suring — koordinatalar avtomatik to‘ladi.': 'Click on the map or drag the icon — the coordinates will be filled in automatically.',
    'Yangilik / eʼlon': 'News / announcement',
    'Yangiliklar va eʻlonlar': 'News and announcements',
    'Yangiliklar va eʼlonlar': 'News and announcements',
    'Yoqilgan': 'Enabled',
    'Yorliq matni': 'Label text',
    'Yorliq va sarlavha': 'Label and title',
    'YouTube, Vimeo yoki embed havola.': 'YouTube, Vimeo or embed link.',
    'YouTube/Vimeo havola yoki video fayl yuklang.': 'Upload a YouTube/Vimeo link or video file.',
    'Yoʻnalishlar': 'Directions',
    'Yoʻnaltiruvchi': 'Referrer',
    'Zamonaviy taʻlim markazi. Biz bilan farzandingiz kelajagiga ishonchli qadam qoʻying.': "Modern educational center. Take a confident step into your child's future with us.",
    'oʻrtacha': 'average',
    'yangi oʻquvchi': 'new students',
    # --- CEFR QR-skaner (admin_qr_scanner.js) ---
    '📷 QR kodni skanerlash': '📷 Scan QR code',
    'Yopish': 'Close',
    'Topildi:': 'Found:',
    'Kamera ochilmoqda…': 'Opening camera…',
    'QR kodni kameraga toʻgʻrilang…': 'Point the camera at the QR code…',
    'Kameraga ruxsat berilmadi:': 'Camera access denied:',
    'Bu brauzerda kamera ishlamaydi. Havolani qoʻlda kiriting.': "The camera doesn't work in this browser. Enter the link manually.",
    # --- Admin / public UI (Unfold helper overrides + PWA) ---
    'Ilovani oʻrnatish': 'Install app',
    'Menyuni ochish yoki yopish': 'Open or close menu',
    'Menyuni yopish': 'Close menu',
    'Show all': 'Show all',
    # --- Theme switch override (templates/unfold/helpers/theme_switch.html) ---
    'Dark': 'Dark',
    'Light': 'Light',
    'System': 'System',
    # --- Hero section (1-/2-tab metric values, floating tabs fieldset) ---
    '1-yorliq — qiymat': 'Tab 1 — value',
    '2-yorliq — qiymat': 'Tab 2 — value',
    'Suzuvchi yorliqlar': 'Floating tabs',
    "Chap yuqoridagi yorliq, masalan «IELTS 7.5» ('oʻrtacha' izohi bilan).":
        'Top-left tab, e.g. «IELTS 7.5» (with an "average" note).',
    "«Bu oy … yangi oʻquvchi» yorlig'idagi raqam, masalan «100+».":
        'The number in the "This month … new students" tab, e.g. "100+".',
    'Hero rasmi ustidagi kichik kartalardagi raqamlar.':
        'Numbers on the small cards above the hero image.',
    # --- Partners (apps/pages/models.py) ---
    'Hamkor': 'Partner',
    'Hamkorlar': 'Partners',
    'Veb-sayt (ixtiyoriy)': 'Website (optional)',
    # --- Certificates ---
    'Havolani ochish': 'Open link',
    'Sertifikat olingan sanasi': 'Certificate issue date',
    'Bu yilda sertifikat topilmadi.': 'No certificates found for this year.',
    'PDF havoladan avtomatik aniqlanadi (topilsa).':
        'Auto-detected from the PDF link (if found).',
    # --- Leads / CRM (apps/leads) ---
    'Lidlar': 'Leads',
    'Manbalar': 'Sources',
    'Manbalar boʻyicha lidlar (CRM)': 'Leads by source (CRM)',
    'Rang': 'Color',
    'Rasm (hisobot uchun)': 'Image (for report)',
    'Himoyalangan': 'Protected',
    'Referrer': 'Referrer',
    'Ruxsat etilmagan manba.': 'Source not allowed.',
    'Hali manba yoʻq.': 'No sources yet.',
    'Material Symbols nomi (masalan: public). Rasm boʻlmaganda ishlatiladi.':
        'Material Symbols name (e.g. public). Used when there is no image.',
    # --- Analytics dashboard (apps/analytics/dashboard.py) ---
    'Bugun': 'Today',
    'Hafta': 'Week',
    'Oy': 'Month',
    'Yil': 'Year',
    'Arizalar (davr)': 'Applications (period)',
    'Yangi arizalar (davr)': 'New applications (period)',
    'Arizalar dinamikasi': 'Applications trend',
    'Tashriflar (davr)': 'Visits (period)',
    'Tashriflar dinamikasi': 'Visits trend',
    'CRM': 'CRM',
    # --- Site config: analytics IDs, Telegram token (apps/siteconfig) ---
    'Google Analytics ID G-XXXXXXX (yoki UA-XXXX-Y) koʻrinishida boʻlishi kerak.':
        'Google Analytics ID must be in the format G-XXXXXXX (or UA-XXXX-Y).',
    'Yandex Metrica ID faqat raqamlardan iborat boʻlishi kerak (masalan: 12345678).':
        'Yandex Metrica ID must consist of digits only (e.g. 12345678).',
    '#RRGGBB. Boʻsh boʻlsa asosiy rang ishlatiladi.':
        '#RRGGBB. If left empty, the primary color is used.',
    'Token holati': 'Token status',
    'Saqlangan tokenni oʻchirish': 'Delete saved token',
    'Belgilansa, paneldagi token oʻchiriladi va .env qiymati ishlatiladi.':
        'If checked, the token in the panel is deleted and the .env value is used.',
    'Xavfsizlik uchun saqlangan token qayta koʻrsatilmaydi. ':
        'For security, the saved token is not shown again. ',
    'Bot tokenini kiriting, soʻng «Telegram qabul qiluvchilar» boʻlimida arizalarni qabul qiladigan adminlarni qoʻshing — bir nechta admin qoʻshish mumkin. Xavfsizlik uchun token bir marta yoziladi va qaytadan koʻrsatilmaydi.':
        'Enter the bot token, then add the admins who receive applications in the «Telegram recipients» section — you can add several. For security, the token is entered once and is never shown again.',
    '• .env qiymati ishlatiladi': '• the .env value is used',
    '✓ Oʻrnatilgan (panel)': '✓ Set (panel)',
    '✗ Oʻrnatilmagan': '✗ Not set',
    # --- Analytics dashboard v2 + privacy/404 (2026-08) ---
    'Maʼlumotlarni yuklab boʻlmadi.': 'Could not load the data.',
    'Qayta urinish': 'Retry',
    'Aniqlanmagan':
        'Unknown',
    'Asliga qaytarish':
        'Reset zoom',
    'Boshlanish sanasi':
        'Start date',
    'Brauzer, qurilma va operatsion tizim':
        'Browser, device and operating system',
    'Brauzerlar':
        'Browsers',
    'Bu davrda maʼlumot yoʻq.':
        'No data for this period.',
    'Butun davr':
        'All time',
    'Butun ekran':
        'Fullscreen',
    'Chiqib ketish darajasi':
        'Bounce rate',
    'Davlatlar':
        'Countries',
    'Jonli':
        'Live',
    'Joylashuv':
        'Locations',
    'Kam':
        'Low',
    'Kattalashtirish':
        'Zoom in',
    'Kichiklashtirish':
        'Zoom out',
    'Koʻp':
        'High',
    'Koʻrish':
        'Views',
    'Mahalliy tarmoq':
        'Local network',
    'Nomaʼlum':
        'Unknown',
    'Operatsion tizimlar':
        'Operating systems',
    'Oʻrtacha davomiylik':
        'Avg. visit duration',
    'Qoʻllash':
        'Apply',
    'Qurilma':
        'Device',
    'Roʻyxat':
        'List',
    'Sahifa koʻrishlari':
        'Page views',
    'Soʻnggi 1 soat':
        'Last hour',
    'Soʻnggi 1 yil':
        'Last year',
    'Soʻnggi 24 soat':
        'Last 24 hours',
    'Soʻnggi 3 oy':
        'Last 3 months',
    'Soʻnggi 30 kun':
        'Last 30 days',
    'Soʻnggi 6 oy':
        'Last 6 months',
    'Soʻnggi 7 kun':
        'Last 7 days',
    'Tanlangan davr':
        'Custom range',
    'Tashrifchi':
        'Users',
    'Texnologiyalar':
        'Technology',
    'Toʻgʻridan-toʻgʻri':
        'Direct / none',
    'Tugash sanasi':
        'End date',
    'Xarita':
        'Map',
    'Ariza qoldirganingizda: ism-familiya, telefon raqam, tanlangan kurs va ixtiyoriy izoh.':
        'When you submit a request: full name, phone number, the selected course and an optional note.',
    'Arizalar faqat markazning masʼul xodimlariga (jumladan Telegram orqali) yetkaziladi. Biz maʼlumotlaringizni uchinchi shaxslarga sotmaymiz. Sayt statistikasi uchun tashqi tahlil xizmatlaridan (masalan Google Analytics, Yandex Metrica) foydalanilishi mumkin.':
        "Requests are delivered only to the centre's responsible staff (including via Telegram). We do not sell your data to third parties. External analytics services (for example Google Analytics, Yandex Metrica) may be used for site statistics.",
    'Arizalar siz bilan bogʻlanish uchun zarur boʻlgan muddat davomida saqlanadi. Tashrif loglari cheklangan muddatdan soʻng avtomatik oʻchiriladi.':
        'Requests are kept for as long as needed to contact you. Visit logs are deleted automatically after a limited period.',
    'Arizangiz boʻyicha siz bilan bogʻlanish va kurslar haqida maʼlumot berish.':
        'To contact you about your request and provide information about courses.',
    'Cookie va lokal saqlash':
        'Cookies and local storage',
    'Tagayev Methods maxfiylik siyosati: qanday maʼlumotlar yigʻiladi va qanday ishlatiladi.':
        'Tagayev Methods privacy policy: what data is collected and how it is used.',
    'Maxfiylik siyosati':
        'Privacy policy',
    'Maʼlumotlar kim bilan ulashiladi':
        'Who the data is shared with',
    'Maʼlumotlardan qanday foydalaniladi':
        'How the data is used',
    'Maʼlumotlarni saqlash muddati':
        'How long data is kept',
    'Oxirgi yangilanish':
        'Last updated',
    'Oʻzingiz haqingizdagi maʼlumotlarni koʻrish, tuzatish yoki oʻchirishni soʻrashingiz mumkin. Buning uchun quyidagi aloqa maʼlumotlari orqali bogʻlaning.':
        'You may request access to, correction of, or deletion of your data. To do so, contact us using the details below.',
    'O‘quvchilarimizning erishgan natijalari (CEFR va boshqa sertifikatlar) yutuqlar namunasi sifatida saytda e’lon qilinishi mumkin. Bunda sertifikat tasviri va o‘quvchi ismi ko‘rsatiladi. Ular faqat o‘quvchi yoki uning qonuniy vakili roziligi bilan joylashtiriladi. Sertifikatingizni saytdan olib tashlashni istasangiz, quyidagi aloqa orqali murojaat qiling — biz zudlik bilan o‘chiramiz.':
        "Our students' results (CEFR and other certificates) may be published on the site as examples of achievement. The certificate image and the student's name are shown. They are published only with the consent of the student or their legal guardian. If you would like your certificate removed from the site, contact us using the details below — we will delete it immediately.",
    'Qanday maʼlumotlar yigʻiladi':
        'What data is collected',
    'Sayt tanlagan tilingiz va yorugʻ/qorongʻu rejimni brauzeringizda saqlaydi. Statistika xizmatlari oʻz cookie fayllaridan foydalanishi mumkin.':
        'The site stores your chosen language and light/dark theme in your browser. Analytics services may use their own cookies.',
    'Saytga tashrif buyurganingizda avtomatik: IP-manzil, brauzer turi va koʻrilgan sahifalar (statistika uchun).':
        'Automatically when you visit the site: IP address, browser type and pages viewed (for statistics).',
    'Sertifikatlar (o‘quvchi yutuqlari)':
        'Certificates (student achievements)',
    'Sizning huquqlaringiz':
        'Your rights',
    'Xizmat sifatini va sayt ishlashini yaxshilash (umumlashtirilgan statistika).':
        'To improve service quality and site performance (aggregated statistics).',
    'Sahifa topilmadi':
        'Page not found',
    'Kechirasiz, siz qidirgan sahifa mavjud emas yoki koʻchirilgan.':
        'Sorry, the page you are looking for does not exist or has been moved.',
    'Xatolik yuz berdi. Iltimos, qaytadan urinib koʻring.':
        'Something went wrong. Please try again.',
    'Yuborilmoqda…':
        'Sending…',
    'Rasmni kattalashtirish':
        'Enlarge image',
    'Hero blokidagi katta rasm/poster.':
        'The large image/poster in the hero block.',
    'Google xarita — qo‘lda override (ixtiyoriy)':
        'Google Map — manual override (optional)',
    'Faqat maxsus Google embed kerak bo‘lsa to‘ldiring. Bo‘sh ':
        'Fill in only if a custom Google embed is needed. Empty ',
}

UNFOLD_UZ = {
    'Add row': "Qator qo'shing",
    'All applications': 'Barcha ilovalar',
    'Apply Filters': "Filtrlarni qo'llash",
    'Cancel': 'Bekor qilish',
    'Change': "O'zgartirish",
    'Change password': "Parolni o'zgartirish",
    'Choose file to upload': 'Yuklash uchun fayl tanlang',
    'Clear': 'Tozalash',
    'Clear all filters': 'Barcha filtrlarni tozalang',
    'Click to cancel': 'Bekor qilish uchun bosing',
    'Click to download': 'Yuklab olish uchun bosing',
    'Close': 'Yopish',
    'Dark': "Qorong'i",
    'Delete': 'Oʻchirish',
    'Expand row': 'Qatorni kengaytirish',
    'False': 'Notoʻgʻri',
    'Filters': 'Filtrlar',
    'General': 'Umumiy',
    'Go back': 'Orqaga qayt',
    # --- Login page (unfold/templates/admin/login.html + helpers) ---
    'Return to site': 'Saytga qaytish',
    'Welcome back to': 'Xush kelibsiz',
    'Hide counts': 'Hisoblarni yashirish',
    'Light': 'Yorugʻ',
    'Log in again': 'Qaytadan kiring',
    'Log out': 'Chiqish',
    'More actions': "Ko'proq harakatlar",
    'Navigate': 'Oʻtish',
    'Next': 'Keyingi',
    'No data': 'Maʼlumot yoʻq',
    'No results found': 'Hech qanday natija topilmadi',
    'Nothing matched your search': 'Qidiruvingizga hech narsa mos kelmadi',
    'Previous': 'Oldingi',
    'Recent searches': 'Oxirgi qidiruvlar',
    'Record picture': 'Rasmni yozib oling',
    'Remove': "O'chirish",
    'Reset filters': 'Filtrlarni tiklash',
    'Run': 'Bajarish',
    'Run the selected action': 'Tanlangan amalni bajaring',
    'Save': 'Saqlash',
    'Save and add another': "Saqlash va boshqasini qo'shish",
    'Save and continue editing': 'Saqlash va tahrirni davom ettirish',
    'Save and view': "Saqlash va ko'rish",
    'Save as new': 'Yangi sifatida saqlang',
    'Select': 'Tanlang',
    'Select all rows': 'Barcha qatorlarni tanlang',
    'Select record': 'Yozuvni tanlash',
    'Show counts': "Hisoblarni ko'rsatish",
    'Submit': 'Yuborish',
    'System': 'Tizim',
    'This item will be deleted.': 'Bu element oʻchirib tashlanadi.',
    'This page yielded into no results. Create a new item or reset your filters.': "Bu sahifa hech qanday natija bermadi. Yangi element yarating yoki filtrlaringizni qayta o'rnating.",
    'Toggle password visibility': 'Parolning koʻrinishini oʻzgartirish',
    'True': 'Toʻgʻri',
    'Type to search': 'Qidirish uchun yozing',
    'Unknown': "Noma'lum",
    'View': 'Koʻrish',
    'View site': "Saytni ko'rish",
    'Search apps and models...': 'Ilova va modellarni qidirish...',
}

UNFOLD_RU = {
    'Add row': 'Добавить строку',
    'All applications': 'Все приложения',
    'Apply Filters': 'Применить фильтры',
    'Cancel': 'Отмена',
    'Change': 'Изменить',
    'Change password': 'Изменить пароль',
    'Choose file to upload': 'Выберите файл для загрузки',
    'Clear': 'Очистить',
    'Clear all filters': 'Очистить все фильтры',
    'Click to cancel': 'Нажмите, чтобы отменить',
    'Click to download': 'Нажмите, чтобы скачать',
    'Close': 'Закрыть',
    'Dark': 'Тёмная',
    'Delete': 'Удалить',
    'Expand row': 'Развернуть строку',
    'False': 'Ложь',
    'Filters': 'Фильтры',
    'General': 'Общее',
    'Go back': 'Вернуться назад',
    # --- Login page (unfold/templates/admin/login.html + helpers) ---
    'Return to site': 'Вернуться на сайт',
    'Welcome back to': 'С возвращением в',
    'Hide counts': 'Скрыть количество',
    'Light': 'Светлая',
    'Log in again': 'Войдите снова',
    'Log out': 'Выйти',
    'More actions': 'Дополнительные действия',
    'Navigate': 'Навигация',
    'Next': 'Далее',
    'No data': 'Нет данных',
    'No results found': 'Результаты не найдены',
    'Nothing matched your search': 'Ничего не соответствует вашему запросу',
    'Previous': 'Предыдущий',
    'Recent searches': 'Недавние поиски',
    'Record picture': 'Изображение записи',
    'Remove': 'Удалить',
    'Reset filters': 'Сбросить фильтры',
    'Run': 'Выполнить',
    'Run the selected action': 'Запустить выбранное действие',
    'Save': 'Сохранить',
    'Save and add another': 'Сохранить и добавить еще',
    'Save and continue editing': 'Сохранить и продолжить редактирование',
    'Save and view': 'Сохранить и просмотреть',
    'Save as new': 'Сохранить как новый',
    'Select': 'Выбрать',
    'Select all rows': 'Выбрать все строки',
    'Select record': 'Выбрать запись',
    'Show counts': 'Показать количество',
    'Submit': 'Отправить',
    'System': 'Системная',
    'This item will be deleted.': 'Этот элемент будет удален.',
    'This page yielded into no results. Create a new item or reset your filters.': 'Эта страница не дала результатов. Создайте новый элемент или сбросьте фильтры.',
    'Toggle password visibility': 'Переключить видимость пароля',
    'True': 'Правда',
    'Type to search': 'Введите для поиска',
    'Unknown': 'Неизвестно',
    'View': 'Посмотреть',
    'View site': 'Посмотреть сайт',
    'Search apps and models...': 'Поиск приложений и моделей...',
}

